services:
  users-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: users-service
    image: store-app/users-service:latest
    container_name: users-service
    ports:
      - "8081:8081"

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: orders-service
    image: store-app/orders-service:latest
    container_name: orders-service
    ports:
      - "8082:8082"

  products-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: products-service
    image: store-app/products-service:latest
    container_name: products-service
    ports:
      - "8083:8083"
